# Generated by Django 5.0 on 2024-05-21 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_delete_user_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
