# Generated by Django 5.0 on 2024-07-05 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=1200)),
                ('price', models.IntegerField()),
                ('condition', models.CharField(max_length=100)),
                ('image', models.URLField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, default='Watch', null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
