# Generated by Django 5.0 on 2024-06-28 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('seller', '0008_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, default='Watch', null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
        ),
    ]
